apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-mysql-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  
  storageClassName: k8s-storageclass
---  
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: db
  namespace: zabbix
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-server
  selector:
    name: mysql-server
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zabbix-server 
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zabbix-proxy-sqlite3
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zabbix-proxy-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-java-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10050
    targetPort: 10050
    name: zabbix-agent
  selector:
    name: zabbix-agent
---
apiVersion: v1
kind: ReplicationController 
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: zabbix
        tier: mysql-server
    spec:
      volumes:
       - name: zabbix-mysql-data
         persistentVolumeClaim:
          claimName: zabbix-mysql-data-claim
      containers:
        - name: zabbix-db
          image: mysql:5.7
          args: 
            - "--character-set-server=utf8"  
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
           - mountPath: "/var/lib/mysql/"
             name: zabbix-mysql-data
             subPath: mysqld.cnf
             readOnly: false
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_STARTPROXYPOLLERS
            value: "5"
          - name: ZBX_PROXYCONFIGFREQUENCY
            value: "60"
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:ubuntu-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 162
            protocol: UDP
            name: snmp-trap
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
      volumes:
       - hostPath:
          path: /zabbix/
         name: zabbix-db-storage
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-proxy-sqlite3
        app: zabbix
    spec:
      containers:
        - name: zabbix-proxy-sqlite3
          image: zabbix/zabbix-proxy-sqlite3:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy-passive"
          - name: ZBX_CONFIGFREQUENCY
            value: "60"
          - name: ZBX_PROXYMODE
            value: "1"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-proxy-mysql
        app: zabbix
    spec:
      containers:
        - name: zabbix-proxy-mysql
          image: zabbix/zabbix-proxy-mysql:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix_proxy"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
    tier: java
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-java-gateway
        app: zabbix
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10052
            protocol: TCP
            name: zabbix-jmx
          env:
          - name: ZBX_TIMEOUT
            value: "5"
---
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-nodeport
  labels:
    app: zabbix
    tier: web
spec:
  type: NodePort
  selector:
    name: zabbix-web
  ports:
   - name: web-http
     port: 8080
     targetPort: 8080
     #nodePort: 30080
     protocol: TCP
---     
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: zabbix-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-web-env
  labels:
    app: zabbix
    tier: web
data:
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zbx_password"
  MYSQL_ROOT_PASSWORD: "some_test_pass"
  ZBX_POSTMAXSIZE: "64M"
  ZBX_MEMORYLIMIT: "256M"
  TZ: "Asia/Shanghai"
  PHP_TZ: "Asia/Shanghai"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
        tier: web
    spec:
      initContainers:
      - name: performance-tunning
        image: busybox:1.34
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/sh
        - -c
        - |
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.ipv4.ip_local_port_range="1024 65535"
            sysctl -w net.ipv4.conf.all.accept_redirects=0
            sysctl -w net.ipv4.conf.all.secure_redirects=0
            sysctl -w net.ipv4.conf.all.send_redirects=0
        securityContext:
          privileged: true
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          #allowPrivilegeEscalation: false
          #runAsUser: 0
        ports:
        - containerPort: 8080
          name: web-http
        - containerPort: 8443
          name: web-https
        resources:
            limits:
              cpu: 700m
              memory: "512M"
            requests:
              cpu: 500m
              memory: "256M"
        livenessProbe:
          httpGet:
            path: /
            port: web-http
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        # Se usa envFrom para configurar TODOS los datos de ConfigMap como variables del contenedor
        envFrom:
        - configMapRef:
            name: zabbix-web-env
      terminationGracePeriodSeconds: 10
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

--- 
apiVersion: v1
kind: List
metadata:
 namespace: zabbix
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
     name: db-secret
     namespace: zabbix
    data:
     db-root-pass: "c29tZV90ZXN0X3Bhc3M="
     db-zbx-user: "emFiYml4"
     db-zbx-pass: "emJ4X3Bhc3N3b3Jk"
