---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-env
  labels:
    app: zabbix
    tier: agent
data:
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  ZBX_PASSIVE_ALLOW: "true"
  ZBX_STARTAGENTS: "3"
  ZBX_TIMEOUT: "10"
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-server-env
  labels:
    app: zabbix
    tier: server
data:
  DB_SERVER_HOST: "zabbix-db"
  DB_SERVER_PORT: "5432"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "Secret*1313"
  POSTGRES_DB: "zabbix"
  TZ: "Europe/Madrid"
  ZBX_DEBUGLEVEL: "3"
  ZBX_CACHESIZE: "1024M"
  ZBX_TRENDCACHESIZE: "1024M"
  ZBX_HISTORYCACHESIZE: "2048M"
  ZBX_HISTORYINDEXCACHESIZE: "1024M"
  ZBX_STARTTRAPPERS: "5"
  ZBX_STARTPREPROCESSORS: "10"
  ZBX_STARTDBSYNCERS: "10"
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-web-env
  labels:
    app: zabbix
    tier: web
data:
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  ZBX_DB_VERIFY_HOST: "true"
  DB_SERVER_HOST: "zabbix-db"
  DB_SERVER_PORT: "5432"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "Secret*1313"
  POSTGRES_DB: "zabbix"
  ZBX_POSTMAXSIZE: "64M"
  ZBX_MEMORYLIMIT: "256M"
  TZ: "Europe/Madrid"
  PHP_TZ: "Europe/Madrid"
  ZBX_SERVER_NAME: "Zabbix on K8s"
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
        tier: server
    spec:
      initContainers:
      - name: pgsql-client-initializer
        image: postgres:13.4
        imagePullPolicy: "IfNotPresent"
        command: ['bash', '-c', 'until pg_isready -h zabbix-db -p 5432;
          do echo waiting for database; sleep 2; done']
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-5.4-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            name: masterport
            protocol: TCP
          securityContext:  
            privileged: true
            #allowPrivilegeEscalation: false
            #runAsUser: 0

#          livenessProbe:
#            tcpSocket:
#              port: masterport
#            initialDelaySeconds: 5
#            periodSeconds: 3
#          readinessProbe:
#            tcpSocket:
#              port: masterport
#            initialDelaySeconds: 10
#            periodSeconds: 5

          envFrom:
          - configMapRef:
              name: zabbix-server-env

        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-5.4-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10050
          envFrom:
          - configMapRef:
              name: zabbix-agent-env
          # Para monitorear recursos del sistema el contenedor debe ser privilegiado
          securityContext:
            privileged: true
#            allowPrivilegeEscalation: false
#            runAsUser: 0
---
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  ports:
  - name: port-trapper
    port: 10051
    protocol: TCP
    targetPort: 10051
  - name: port-agent
    port:  10050
    protocol: TCP
    targetPort: 10050

  selector:
    name: zabbix-server
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
        tier: web
    spec:
      initContainers:
      - name: performance-tunning
        image: busybox:1.34
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/sh
        - -c
        - |
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.ipv4.ip_local_port_range="1024 65535"
            sysctl -w net.ipv4.conf.all.accept_redirects=0
            sysctl -w net.ipv4.conf.all.secure_redirects=0
            sysctl -w net.ipv4.conf.all.send_redirects=0
        securityContext:
          privileged: true
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-5.4-latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          #allowPrivilegeEscalation: false
          #runAsUser: 0
        ports:
        - containerPort: 8080
          name: web-http
        - containerPort: 8443
          name: web-https
        resources:
            limits:
              cpu: 700m
              memory: "512M"
            requests:
              cpu: 500m
              memory: "256M"
        livenessProbe:
          httpGet:
            path: /
            port: web-http
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        # Se usa envFrom para configurar TODOS los datos de ConfigMap como variables del contenedor
        envFrom:
        - configMapRef:
            name: zabbix-web-env
      terminationGracePeriodSeconds: 10
---
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-nodeport
  labels:
    app: zabbix
    tier: web
spec:
  type: NodePort
  selector:
    name: zabbix-web
  ports:
   - name: web-http
     port: 8080
     targetPort: 8080
     #nodePort: 30080
     protocol: TCP
---     
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: zabbix-web

---
